type_mappings:
  text: VARCHAR
  int: INTEGER
  decimal: DECIMAL
  categorical: VARCHAR
  foreign_key: VARCHAR
  datetime: DATE
  default: ANY

sql_dialects:
  mysql: MysqlSqlDialect.DEFAULT
  postgresql: PostgresqlSqlDialect.DEFAULT
  hive: HiveSqlDialect.DEFAULT
  default: CalciteSqlDialect.DEFAULT

schema_path: "src/main/resources/university/schema.yaml"

privacy_models:
  model1: "src/main/resources/university/privacy_models/model1.yaml"
  model2: "src/main/resources/university/privacy_models/model2.yaml"
  model3: "src/main/resources/university/privacy_models/model3.yaml"
  model4: "src/main/resources/university/privacy_models/model4.yaml"

queries:
  1: "
    SELECT COUNT(*)
    FROM student
    GROUP BY u_major
    "
#  1: "
#  SELECT COUNT(u_major)
#  FROM section
#  INNER JOIN course ON s_cid = c_cid
#  INNER JOIN enrollment ON s_sid = e_sid
#  WHERE c_title LIKE 'LLMs'
#  "
  2: "
  SELECT COUNT(*)
  FROM (
        SELECT e_uid, COUNT(*) AS enroll_count
        FROM enrollment
        GROUP BY e_uid
  )
  WHERE enroll_count > 3
  "
  3: "
  SELECT COUNT(*)
  FROM (
        SELECT e_sid, COUNT(*) AS enroll_count
        FROM enrollment
        GROUP BY e_sid
  )
  INNER JOIN enrollment2 ON e_sid = e_sid2
  WHERE enroll_count < 10
  GROUP BY e_uid2
  "
  4: "
  SELECT COUNT(*)
  FROM (
        SELECT e_sid, COUNT(*) AS enroll_count
        FROM enrollment
        GROUP BY e_sid
  )
  INNER JOIN enrollment2 ON e_sid = e_sid2
  WHERE enroll_count > 15
  GROUP BY e_review2
  "
  5: "
  SELECT SUM(e_review)
  FROM section
  INNER JOIN course ON s_cid = c_cid
  INNER JOIN enrollment ON s_sid = e_sid
  WHERE c_title LIKE 'NLP'
  GROUP BY s_fid
  "
  6: "
  SELECT COUNT(e_review)
  FROM section
  INNER JOIN course ON s_cid = c_cid
  INNER JOIN enrollment ON s_sid = e_sid
  WHERE c_title LIKE 'NLP'
  GROUP BY s_fid
  "
