type_mappings:
  text: VARCHAR
  int: INTEGER
  decimal: DECIMAL
  categorical: VARCHAR
  foreign_key: VARCHAR
  datetime: DATE
  default: ANY

sql_dialects:
  mysql: MysqlSqlDialect.DEFAULT
  postgresql: PostgresqlSqlDialect.DEFAULT
  hive: HiveSqlDialect.DEFAULT
  default: CalciteSqlDialect.DEFAULT

schema_path: "src/main/resources/university/schema.yaml"

privacy_models:
  model1: "src/main/resources/university/privacy_models/model1.yaml"
  model2: "src/main/resources/university/privacy_models/model2.yaml"
  model3: "src/main/resources/university/privacy_models/model3.yaml"
  model4: "src/main/resources/university/privacy_models/model4.yaml"

queries:
  1: "
  SELECT COUNT(u_uid)
  FROM student
  "
  2: "
  SELECT COUNT(s_sid)
  FROM section
  INNER JOIN course ON s_cid = c_cid
  INNER JOIN enrollment ON s_sid = e_sid
  WHERE c_title LIKE 'LLMs'
  "
  3: "
  SELECT SUM(e_review)
  FROM section
  INNER JOIN course ON s_cid = c_cid
  INNER JOIN enrollment ON s_sid = e_sid
  WHERE c_title LIKE 'NLP'
  GROUP BY e_uid
  "
