type_mappings:
  text: VARCHAR
  int: INTEGER
  decimal: DECIMAL
  categorical: VARCHAR
  foreign_key: VARCHAR
  datetime: DATE
  default: ANY

sql_dialects:
  mysql: MysqlSqlDialect.DEFAULT
  postgresql: PostgresqlSqlDialect.DEFAULT
  hive: HiveSqlDialect.DEFAULT
  default: CalciteSqlDialect.DEFAULT

schema_path: "src/main/resources/university/schema.yaml"

privacy_models:
  baseline1: "src/main/resources/university/privacy_models/baseline1.yaml"
  baseline2: "src/main/resources/university/privacy_models/baseline2.yaml"
  student1: "src/main/resources/university/privacy_models/student1.yaml"

queries:
  1: "
  SELECT COUNT(*)
  FROM (
        SELECT e_sid, COUNT(*) AS enroll_count
        FROM enrollment
        GROUP BY e_sid
  )
  INNER JOIN enrollment2 ON e_sid = e_sid2
  WHERE enroll_count < 10
  GROUP BY e_uid2
  "
  2: "
  SELECT COUNT(*)
  FROM (
        SELECT e_sid, COUNT(*) AS enroll_count
        FROM enrollment
        GROUP BY e_sid
  )
  INNER JOIN enrollment2 ON e_sid = e_sid2
  WHERE enroll_count > 15
  GROUP BY e_review2
  "
  3: "
  SELECT COUNT(*)
  FROM (
        SELECT e_uid, COUNT(*) AS enroll_count
        FROM enrollment
        GROUP BY e_uid
  )
  INNER JOIN scholarship ON e_uid = sc_uid
  WHERE enroll_count > 4
  "
  4: "
  SELECT SUM(e_review)
  FROM section
  INNER JOIN enrollment ON s_sid = e_sid
  GROUP BY s_fid
  "
  5: "
  SELECT COUNT(e_review)
  FROM section
  INNER JOIN enrollment ON s_sid = e_sid
  GROUP BY s_fid
  "
