type_mappings:
  text: VARCHAR
  int: INTEGER
  decimal: DECIMAL
  categorical: VARCHAR
  foreign_key: VARCHAR
  datetime: DATE
  default: ANY

sql_dialects:
  mysql: MysqlSqlDialect.DEFAULT
  postgresql: PostgresqlSqlDialect.DEFAULT
  hive: HiveSqlDialect.DEFAULT
  default: CalciteSqlDialect.DEFAULT

schema_path: "src/main/resources/tpch/schema.yaml"

privacy_models:
  baseline_customer: "src/main/resources/tpch/privacy_models/baseline_customer.yaml"
#  baseline_supplier: "src/main/resources/tpch/privacy_models/baseline_supplier.yaml"
  customer1: "src/main/resources/tpch/privacy_models/customer1.yaml"
  customer2: "src/main/resources/tpch/privacy_models/customer2.yaml"
  customer3: "src/main/resources/tpch/privacy_models/customer3.yaml"
  customer4: "src/main/resources/tpch/privacy_models/customer4.yaml"

queries:
  1: "
  SELECT  
          count(*)
  FROM 
          lineitem
  WHERE
          l_shipdate <= date '1998-12-01' - INTERVAL '60' day (3)
  GROUP BY
          l_returnflag,
          l_linestatus
  "
  4: "
    SELECT 
            o_orderpriority, 
            count(*) AS order_count
    FROM  
            orders
    INNER JOIN lineitem ON o_orderkey = l_orderkey
    WHERE 
            o_orderdate >= date '1993-07-01'
            AND o_orderdate < date '1993-07-01' + interval '3' month
            AND l_commitdate < l_receiptdate
    GROUP BY 
            o_orderpriority
  "
  13: "
  SELECT 
          count(*) AS custdist
  FROM (
          SELECT 
                  c_custkey, 
                  count(o_orderkey) AS c_count
          FROM customer 
          LEFT OUTER JOIN orders ON c_custkey = o_custkey
          WHERE o_comment NOT LIKE '%special%requests%'
          GROUP BY c_custkey
  )
  GROUP BY 
          c_count
  "
  16: "
  SELECT
          p_brand,
          p_type,
          p_size,
          COUNT(DISTINCT ps_suppkey) AS supplier_cnt
  FROM
          partsupp
  INNER JOIN part ON ps_partkey = p_partkey
  LEFT OUTER JOIN supplier ON ps_suppkey = s_suppkey
  WHERE
          p_brand <> 'Brand#45'
          AND p_type NOT LIKE 'MEDIUM POLISHED%'
          AND p_size IN (49, 14, 23, 45, 19, 3, 36, 9)
          AND s_comment LIKE '%Customer%Complaints%'
          AND ps_suppkey IS NULL
  GROUP BY
          p_brand,
          p_type,
          p_size
  "